### ISSUE TITLE
URL in description is invalid

### ISSUE THREAD

**Issue by dmuth** [poush/monsterInMe#1]
Description reads:

> 👹Get your self a monster name http://ipiyush/monsterInMe

I tried the URL and it is invalid.

(I found this project from https://github.audio/, BTW)

-- Doug

**Comment by poush** [comment]
Thanks for notifying. I have updated link to correct one.

**Comment by dmuth** [comment]
Thanks.  I just tried out the app, that's pretty neat!  I'll let some of my friends know. :-)
