### ISSUE TITLE
New Name button not visible

### ISSUE THREAD

**Issue by jeevan-jp** [poush/monsterInMe#2]
`<button type="button" class="btn" onclick="window.location.reload()"> New Name? Try Again </button>`
This button is not visible after getting first monstrous name (In my PC running windows 10)

**Comment by poush** [comment]
@jeevan-jp Can you please provide screenshots? And please if you would like to work on this then feel free to send the PR

**Comment by jeevan-jp** [comment]
![img_20170907_160043](https://user-images.githubusercontent.com/26577556/30159564-a1e18c8c-93e6-11e7-8e12-03b89640f887.jpg)

**Comment by jeevan-jp** [comment]
Screenshot for the same
